Repository microsoft/garnet, pull requests merged in 2024-06, with the labels that each got.

#442 Missing configuration switch in dotnet test
  .github/workflows/ci.yml
Labels: ci/cd

#443 Removing key from object store when collection object it empty
  libs/server/Custom/CustomObjectBase.cs
  libs/server/Objects/Hash/HashObject.cs
  libs/server/Objects/List/ListObject.cs
  libs/server/Objects/Set/SetObject.cs
  libs/server/Objects/SortedSet/SortedSetObject.cs
  libs/server/Objects/Types/GarnetObjectBase.cs
  libs/server/Objects/Types/IGarnetObject.cs
  libs/server/Resp/Objects/ListCommands.cs
  libs/server/Resp/Objects/SortedSetCommands.cs
  libs/server/Storage/Functions/MainStore/RMWMethods.cs
  libs/server/Storage/Functions/ObjectStore/RMWMethods.cs
  libs/server/Storage/Functions/ObjectStore/ReadMethods.cs
  libs/server/Storage/Session/ObjectStore/Common.cs
  libs/storage/Tsavorite/cs/benchmark/SessionFunctions.cs
  libs/storage/Tsavorite/cs/src/core/Allocator/AllocatorScan.cs
  libs/storage/Tsavorite/cs/src/core/ClientSession/SessionFunctionsWrapper.cs
  libs/storage/Tsavorite/cs/src/core/Compaction/LogCompactionFunctions.cs
  libs/storage/Tsavorite/cs/src/core/Index/Interfaces/ISessionFunctions.cs
  libs/storage/Tsavorite/cs/src/core/Index/Interfaces/ISessionFunctionsWrapper.cs
  libs/storage/Tsavorite/cs/src/core/Index/Interfaces/SessionFunctionsBase.cs
  libs/storage/Tsavorite/cs/src/core/Index/Tsavorite/Implementation/InternalRMW.cs
  libs/storage/Tsavorite/cs/src/core/Utilities/Status.cs
  libs/storage/Tsavorite/cs/src/core/Utilities/StatusCode.cs
  libs/storage/Tsavorite/cs/test/AdvancedLockTests.cs
  libs/storage/Tsavorite/cs/test/PostOperationsTests.cs
  libs/storage/Tsavorite/cs/test/RevivificationTests.cs
  main/GarnetServer/Extensions/MyDictObject.cs
  test/Garnet.test/RespHashTests.cs
  test/Garnet.test/RespListTests.cs
  test/Garnet.test/RespSetTest.cs
  test/Garnet.test/RespSortedSetTests.cs
  test/Garnet.test/RespTransactionProcTests.cs
Labels: bug

#475 Removed stub for COMMAND DOCS
  libs/server/Resp/BasicCommands.cs
  libs/server/Resp/Parser/RespCommand.cs
  libs/server/Resp/RespCommandsInfo.cs
  libs/server/Resp/RespCommandsInfo.json
  libs/server/Resp/RespServerSession.cs
  playground/CommandInfoUpdater/SupportedCommand.cs
  test/Garnet.test/Resp/ACL/RespCommandTests.cs
  test/Garnet.test/RespCommandTests.cs
Labels: API

#356 Blocking command support (BLPOP/BRPOP & BLMOVE)
  libs/host/GarnetServer.cs
  libs/server/AOF/AofProcessor.cs
  libs/server/API/IGarnetApi.cs
  libs/server/Objects/ItemBroker/CollectionItemBroker.cs
  libs/server/Objects/ItemBroker/CollectionItemBrokerEvent.cs
  libs/server/Objects/ItemBroker/CollectionItemObserver.cs
  libs/server/Objects/ItemBroker/CollectionItemResult.cs
  libs/server/Objects/List/ListObject.cs
  libs/server/Providers/GarnetProvider.cs
  libs/server/Resp/LocalServerSession.cs
  libs/server/Resp/Objects/ListCommands.cs
  libs/server/Resp/Parser/RespCommand.cs
  libs/server/Resp/RespCommandsInfo.json
  libs/server/Resp/RespServerSession.cs
  libs/server/Storage/Session/ObjectStore/ListOps.cs
  libs/server/Storage/Session/StorageSession.cs
  playground/CommandInfoUpdater/CommandInfoUpdater.cs
  playground/CommandInfoUpdater/SupportedCommand.cs
  playground/Embedded.perftest/EmbeddedRespServer.cs
  test/Garnet.test/Resp/ACL/RespCommandTests.cs
  test/Garnet.test/RespBlockingListTests.cs
  website/docs/commands/api-compatibility.md
  website/docs/commands/data-structures.md
  website/docs/dev/collection-broker.md
  website/sidebars.js
Labels: enhancement, API

#497 Change in release pipeline to the new code signing infrastructure
  .azure/pipelines/azure-pipelines-external-release.yml
Labels: ci/cd
